# Site settings
title: "Prakhar Singh"
description: "Strategy & Planning @ Uber Eats ANZ. Writing about work, travel, coffee and AI."
url: "https://prakharsingh.com"
baseurl: ""  # leave blank for user site or custom domain
timezone: "Australia/Melbourne"
lang: "en-AU"
logo: "/assets/og.png"
favicon: "/assets/og.png"  # temporary; replace with your photo at /assets/favicon.png and update this path

# Theme
remote_theme: pages-themes/minimal@v0.2.0

# Plugins supported by GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - AGENTS.md

# Build settings
markdown: kramdown
permalink: pretty

# Author block (used by SEO tag)
author:
  name: "Prakhar Singh"
  email: "prkhr.singh+website@gmail.com"
  links:
  - label: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/prkhrsingh"
  - label: "X"
    icon: "fab fa-twitter"
    url: "https://x.com/prkhr"
  - label: "Instagram"
    icon: "fab fa-instagram"
    url: "https://www.instagram.com/prakhar_singh/"
  - label: "Substack"
    icon: "fas fa-newspaper"
    url: "https://substack.com/@prakharsingh"

# SEO Tag settings
twitter:
  username: prkhr

# Feed
feed:
  path: feed.xml

# Search/analytics (optional)
# Paste tokens/IDs here to enable meta verification and analytics snippets.
# After updating, Pages deploy picks them up automatically.
google_site_verification: ""   # e.g., ABCDEFG12345 from Google Search Console
bing_site_verification: ""     # e.g., 12345ABCDE from Bing Webmaster Tools
google_analytics_id: ""        # e.g., G-XXXXXXXXXX (GA4)
plausible_domain: ""           # e.g., prakharsingh.com (for Plausible)
